### ISSUE TITLE
hclfmt on a range?

### ISSUE THREAD

**Issue by zachgersh** [fatih/hclfmt#10]
Hey @fatih,

Love the project and all the work you do in general. Was wondering if you'd be open to having hclfmt work on a range?

I have a project with some string literals that contain HCL and they are not formatted nicely (but I want them to be). 

Cheers

**Comment by fatih** [comment]
Hi @zachgersh 

Thanks for the kind words. Can you open the issue to: https://github.com/hashicorp/hcl ? Because `hclfmt` uses `hcl/printer` under the hood, which is part of `hashicorp/hcl`.
