### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by vrenjith** [fatih/hclfmt#12]
Hi Faith, 

Could you please do a build for linux (amd64) and update a release so that we all need not build the binary locally and can refer to the releases? If you can give me permission, I can upload a release too.

-Renjith

**Comment by fatih** [comment]
# Archived project. No maintenance. 

This project is not maintained anymore and is archived. Feel free to fork and
make your own changes if needed. For more detail read my blog post: [Taking an indefinite sabbatical from my projects](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks to everyone for their valuable feedback and contributions.
