### ISSUE TITLE
Multiple comment lines split by newlines

### ISSUE THREAD

**Issue by jfexyz** [fatih/hclfmt#3]
Maybe this is desired behavior, but currently hclfmt converts this:

```
### comment line one
### comment line two
provider "aws" {
  foo = "bar"
}
```

as:

```
### comment line one

### comment line two
provider "aws" {
  foo = "bar"
}
```

It correctly (IMO) keeps the second comment directly above the provider object, but otherwise splits the comments.

I know multiline comments can be created with `/**/`, but the current behavior still seems odd.

**Comment by mssola** [comment]
I used to be able to reproduce this, but I no longer can with master hcl.

**Comment by fatih** [comment]
@joshuajabbour can you please update hclfmt and try it again?

**Comment by jfexyz** [comment]
This is also no longer occurring for me.
