### ISSUE TITLE
Empty block formatting

### ISSUE THREAD

**Issue by joshuaspence** [fatih/hclfmt#5]
Currently, `hclfmt` doesn't seem to allow the following formatting:

```
variable "foobar" {}
```

Instead, this will be changed to:

```
variable "foobar" {
}
```

This seems odd to me and I'm not sure if this is intentional.

**Comment by mssola** [comment]
This should be fixed with hashicorp/hcl#101.

**Comment by fatih** [comment]
Thanks @mssola for the notice. Closing this.
