### ISSUE TITLE
Question regarding formatting terraform?

### ISSUE THREAD

**Issue by cxhercules** [fatih/hclfmt#9]
Is the intent also to do formatting for terraform since it also follows the hcl standard? I have been using https://github.com/mattaitchison/atom-terraform-fmt to get away from discussions over space, newline, and alignment, hoping against hope :). Right now of course in atom editor the .tf files or .tfvars do not get picked up by hclfmt atom plugin.  

Thank you!

**Comment by fatih** [comment]
This uses the same `printer` what terraform uses. I wrote the initial Printer actually (which is moved now to here: https://github.com/hashicorp/hcl). Terraforms' `fmt` command is for terraform specific files. However note that `HCL` is universal and can be used by anyone. thanks
